services:
  - type: web
    name: omsorgsplus
    env: node
    region: frankfurt
    plan: starter
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        value: https://omsorgsplus.se
      - key: MONGO_URL
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
